### PR TITLE
Miscellaneous touchups

### PR DESCRIPTION
**Pull request by beemeeupnow**
* fixed an issue where all tests after completion of `test_alchemy_setup.py` would fail
* updated requirements.txt to allow latest without allowing major version increments
* fixed an issue where list type hints were causing errors
* ordering of imports and removal of unused imports

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Awesome PR!

Just one ask, can you use [monkeypatch](https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html) like we do in the `conftest` to test the changing of ENV vars?

Something like:
```
monkeypatch.delenv("ALCHEMY_API_KEY", raising=False)
```
Thank you!

**Review by PatrickAlphaC — CHANGES_REQUESTED** [review]
See conversation

**Comment by beemeeupnow** [comment]
Thank you for the recommendation!  

I added it now.

**Comment by beemeeupnow** [comment]
Let me know if that is what you meant or if you were asking for another new test to be added.

**Comment by PatrickAlphaC** [comment]
Yes! This is great (sorry on my delay)! Thank you!

**Pull request merged**
